// @vernaculo/skills — exports a persona as a self-contained Agent Skill
// (https://agentskills.io/specification). The skill needs no Vernáculo package
// at runtime: copy the directory into any agent that supports skills.
import { compile, INSTRUCTIONS_FORMAT, escapeMarkdownInline as md } from "@vernaculo/compiler";
import type { PersonaIR } from "@vernaculo/core";
import { stringify } from "yaml";

export interface SkillFile {
  /** Path relative to the skill directory, always with forward slashes. */
  readonly path: string;
  readonly content: string;
}

export interface SkillExport {
  /** Skill name; the directory holding the files must have this name. */
  readonly name: string;
  readonly files: readonly SkillFile[];
}

export interface SkillExportOptions {
  /** Overrides the derived skill name. Must satisfy the Agent Skills name rules. */
  readonly name?: string | undefined;
}

const NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const MAX_NAME_LENGTH = 64;
const MAX_DESCRIPTION_LENGTH = 1024;

/** Derives a valid Agent Skills name from a persona id: `pt-BR/ba/salvador` → `vernaculo-pt-br-ba-salvador`. */
export function skillName(personaId: string): string {
  const slug = `vernaculo-${personaId}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug.slice(0, MAX_NAME_LENGTH).replace(/-+$/, "");
}

/** Builds the files of an Agent Skill for an IR. Pure and deterministic. */
export function exportSkill(ir: PersonaIR, options: SkillExportOptions = {}): SkillExport {
  const name = options.name ?? skillName(ir.persona.id);
  if (!NAME_PATTERN.test(name) || name.length > MAX_NAME_LENGTH) {
    throw new TypeError(`"${name}" is not a valid Agent Skills name`);
  }

  const references: SkillFile[] = [
    vocabularyReference(ir),
    discourseReference(ir),
    pragmaticsReference(ir),
    examplesReference(ir),
  ].filter((file): file is SkillFile => file !== undefined);
  references.push(sourcesReference(ir));

  const skill: SkillFile = { path: "SKILL.md", content: skillDocument(ir, name, references) };
  return { name, files: [skill, ...references] };
}

function skillDocument(ir: PersonaIR, name: string, references: readonly SkillFile[]): string {
  const { persona } = ir;
  const description =
    `Regional language layer for ${persona.name} (${persona.id}) at intensity ${ir.intensity}. ` +
    `Use when writing in ${persona.language} in this regional variety: it adjusts vocabulary, ` +
    "discourse markers and conversational conventions without changing your role, rules or facts.";

  const frontmatter: Record<string, unknown> = {
    name,
    description: description.slice(0, MAX_DESCRIPTION_LENGTH),
  };
  if (persona.license) frontmatter.license = persona.license;
  frontmatter.metadata = {
    "vernaculo-persona": persona.id,
    "vernaculo-version": persona.version,
    "vernaculo-intensity": String(ir.intensity),
    "vernaculo-maturity": persona.maturity,
    "vernaculo-format": INSTRUCTIONS_FORMAT,
  };

  const body = [
    compile(ir).instructions.trimEnd(),
    "",
    "## Reference files",
    "",
    "Read these only when you need detail (meanings, evidence, sources):",
    "",
    ...references.map((file) => `- [${file.path}](${file.path})`),
    "",
    `Generated by Vernáculo from ${persona.id}@${persona.version}. Edit the persona source and re-export instead of editing this file.`,
  ];
  return `---\n${stringify(frontmatter, { lineWidth: 0 })}---\n\n${body.join("\n")}\n`;
}

interface Detailed {
  readonly evidence?: string | undefined;
  readonly sources?: readonly string[] | undefined;
  readonly notes?: string | undefined;
  readonly minIntensity?: number | undefined;
}

function details(item: Detailed): string[] {
  const facts = [
    item.evidence ? `evidence: ${item.evidence}` : undefined,
    item.sources?.length ? `sources: ${item.sources.join(", ")}` : undefined,
    item.minIntensity !== undefined ? `from intensity ${item.minIntensity}` : undefined,
  ].filter(Boolean);
  return [
    ...(facts.length > 0 ? [`  - ${facts.join("; ")}`] : []),
    ...(item.notes ? [`  - Notes: ${md(item.notes)}`] : []),
  ];
}

function reference(
  path: string,
  title: string,
  sections: [string, string[]][],
): SkillFile | undefined {
  const filled = sections.filter(([, lines]) => lines.length > 0);
  if (filled.length === 0) return undefined;
  const lines = [`# ${title}`];
  for (const [heading, content] of filled) lines.push("", `## ${heading}`, "", ...content);
  return { path, content: `${lines.join("\n")}\n` };
}

function vocabularyReference(ir: PersonaIR): SkillFile | undefined {
  const { discouraged } = ir.vocabulary;
  // Corroborated forms are listed with their evidence; SKILL.md flags them as unconfirmed.
  const preferred = [...ir.vocabulary.preferred, ...ir.corroborated.vocabulary.preferred];
  const contextual = [...ir.vocabulary.contextual, ...ir.corroborated.vocabulary.contextual];
  return reference("references/vocabulary.md", "Vocabulary", [
    [
      "Preferred",
      preferred.flatMap((i) => [
        `- **${md(i.term)}**${i.meaning ? ` — ${md(i.meaning)}` : ""}`,
        ...details(i),
      ]),
    ],
    [
      "Contextual",
      contextual.flatMap((i) => [
        `- **${md(i.term)}** — context: ${md(i.context)}${i.meaning ? `. ${md(i.meaning)}` : ""}`,
        ...details(i),
      ]),
    ],
    [
      "Discouraged",
      discouraged.flatMap((i) => [
        `- **${md(i.term)}**${i.reason ? ` — ${md(i.reason)}` : ""}`,
        ...details(i),
      ]),
    ],
  ]);
}

function discourseReference(ir: PersonaIR): SkillFile | undefined {
  return reference("references/discourse.md", "Discourse and sentence patterns", [
    [
      "Discourse markers",
      [...ir.discourseMarkers, ...ir.corroborated.discourseMarkers].flatMap((i) => [
        `- **${md(i.form)}** — ${md(i.function)}`,
        ...details(i),
      ]),
    ],
    [
      "Sentence patterns",
      [...ir.morphosyntax, ...ir.corroborated.morphosyntax].flatMap((i) => [
        `- \`${i.id}\` — ${md(i.description)}${i.example ? ` Example: "${md(i.example)}"` : ""}`,
        ...details(i),
      ]),
    ],
  ]);
}

function pragmaticsReference(ir: PersonaIR): SkillFile | undefined {
  const both = (name: keyof PersonaIR["pragmatics"]) => [
    ...ir.pragmatics[name],
    ...ir.corroborated.pragmatics[name],
  ];
  const groups: [string, PersonaIR["pragmatics"]["greetings"]][] = [
    ["Forms of address", both("addressForms")],
    ["Greetings", both("greetings")],
    ["Acknowledgements", both("acknowledgements")],
    ["Disagreements", both("disagreements")],
    ["Closings", both("closings")],
  ];
  return reference(
    "references/pragmatics.md",
    "Conversational conventions",
    groups.map(([heading, items]) => [
      heading,
      items.flatMap((i) => [
        `- **${md(i.form)}**${i.usage ? ` — ${md(i.usage)}` : ""}`,
        ...details(i),
      ]),
    ]),
  );
}

function examplesReference(ir: PersonaIR): SkillFile | undefined {
  return reference("references/examples.md", "Examples and anti-patterns", [
    [
      "Examples",
      ir.examples.flatMap((e) => [
        `- ${md(e.situation)}${e.intensity !== undefined ? ` (intensity ${e.intensity})` : ""}`,
        ...(e.neutral ? [`  - Neutral: "${md(e.neutral)}"`] : []),
        `  - With this layer: "${md(e.text)}"`,
      ]),
    ],
    [
      "Anti-patterns (never produce)",
      ir.antiPatterns.flatMap((a) => [
        `- "${md(a.text)}"`,
        `  - ${a.category}: ${md(a.explanation)}`,
      ]),
    ],
  ]);
}

function sourcesReference(ir: PersonaIR): SkillFile {
  const { persona } = ir;
  const lines = [
    "# Sources and provenance",
    "",
    `- Persona: \`${persona.id}\` version ${persona.version}`,
    `- Maturity: ${persona.maturity}`,
    `- Lineage (root first): ${persona.lineage.map((id) => `\`${id}\``).join(" → ")}`,
    ...(persona.license ? [`- License of the persona content: ${persona.license}`] : []),
    "",
    "## Sources",
    "",
  ];
  if (ir.sources.length === 0) {
    lines.push("No sources are declared.");
  } else {
    for (const source of ir.sources) {
      lines.push(`- \`${source.id}\` — ${md(source.title)} (${source.type}; ${source.usage})`);
      if (source.citation) lines.push(`  - Citation: ${md(source.citation)}`);
      if (source.url) lines.push(`  - URL: ${source.url}`);
      if (source.license) lines.push(`  - License: ${source.license}`);
      if (source.accessed) lines.push(`  - Accessed: ${source.accessed}`);
    }
  }
  return { path: "references/sources.md", content: `${lines.join("\n")}\n` };
}
